import React, { useEffect, useState } from "react";
import { Eye, Printer, RotateCcw, Search } from "lucide-react";
import { formatPrice } from "@/lib/cafeData";
import { fetchOrderById, fetchOrders, updateOrderStatus } from "@/lib/catalogStore";
const METHODS = { cash: "Cash", card: "Card", "e-wallet": "E-wallet", split: "Split" };
export default function History() {
  const [orders, setOrders] = useState([]), [query, setQuery] = useState(""), [filter, setFilter] = useState("all"), [selected, setSelected] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { let cancelled = false; fetchOrders().then((rows) => !cancelled && setOrders(rows)).catch((err) => !cancelled && setError(err.message)).finally(() => !cancelled && setLoading(false)); return () => { cancelled = true; }; }, []);
  const visible = orders.filter((order) => (filter === "all" || order.payment_method === filter) && (!query.trim() || order.order_number?.toLowerCase().includes(query.toLowerCase()) || String(order.total).includes(query)));
  const view = async (order) => { setSelected({ ...order, lines: null }); try { setSelected(await fetchOrderById(order.id)); } catch (err) { alert(err.message); setSelected(null); } };
  const refund = async (order) => { if (!confirm(`Refund order #${order.order_number}?`)) return; try { const saved = await updateOrderStatus(order.id, "refunded"); setOrders((rows) => rows.map((row) => row.id === saved.id ? saved : row)); } catch (err) { alert(err.message); } };
  if (loading || error) return <div className={`px-8 py-7 text-sm ${error ? "text-red-400" : "text-[hsl(var(--muted-foreground))]"}`}>{error ? `Couldn't load orders: ${error}` : "Loading orders..."}</div>;
  return <div className="px-8 py-7"><h1 className="text-[28px] font-medium mb-5">Order history</h1><div className="flex flex-wrap gap-3 mb-4"><label className="relative flex-1 min-w-[220px]"><Search size={18} className="absolute left-3 top-3" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by order no. or amount..." className="w-full h-11 pl-10 pr-3 rounded border" /></label><div className="flex gap-2">{["all", "cash", "card", "e-wallet", "split"].map((method) => <button key={method} onClick={() => setFilter(method)} className="h-11 px-3 border rounded text-sm">{method === "all" ? "All methods" : METHODS[method]}</button>)}</div></div><div className="rounded-xl bg-[hsl(var(--card))] border overflow-hidden"><table className="w-full text-sm"><thead><tr className="text-left text-xs border-b"><th className="px-4 py-3">Order</th><th className="px-4 py-3">Date</th><th className="px-4 py-3">Table</th><th className="px-4 py-3">Method</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Total</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{visible.map((order) => <tr key={order.id} className="border-b"><td className="px-4 py-3 font-medium">#{order.order_number?.slice(-6)}</td><td className="px-4 py-3">{new Date(order.created_at).toLocaleString()}</td><td className="px-4 py-3">{order.table_or_address || "—"}</td><td className="px-4 py-3">{METHODS[order.payment_method] || order.payment_method}</td><td className="px-4 py-3">{order.status}</td><td className="px-4 py-3 text-right font-medium">{formatPrice(Number(order.total))}</td><td className="px-4 py-3"><div className="flex justify-end gap-2"><button title="View" onClick={() => view(order)}><Eye size={16} /></button><button title="Reprint" onClick={() => window.print()}><Printer size={16} /></button>{order.status === "completed" && <button title="Refund" onClick={() => refund(order)}><RotateCcw size={16} /></button>}</div></td></tr>)}{!visible.length && <tr><td colSpan="7" className="p-10 text-center">No orders found.</td></tr>}</tbody></table></div>{selected && <OrderModal order={selected} onClose={() => setSelected(null)} />}</div>;
}
function OrderModal({ order, onClose }) { return <div className="fixed inset-0 z-50 bg-black/30 flex items-center justify-center" onClick={onClose}><div className="w-full max-w-md p-5 rounded-xl bg-[hsl(var(--card))]" onClick={(e) => e.stopPropagation()}><div className="font-medium">Order #{order.order_number?.slice(-6)}</div>{!order.lines ? <p className="py-4">Loading order details...</p> : <div className="py-4 space-y-2">{order.lines.map((line) => <div key={line.id} className="flex justify-between"><span>{line.qty}× {line.name_snapshot}</span><span>{formatPrice(Number(line.line_total))}</span></div>)}</div>}<div className="border-t pt-3 space-y-1"><div className="flex justify-between"><span>Subtotal</span><span>{formatPrice(Number(order.subtotal))}</span></div><div className="flex justify-between"><span>Tax</span><span>{formatPrice(Number(order.tax))}</span></div><div className="flex justify-between font-medium"><span>Total</span><span>{formatPrice(Number(order.total))}</span></div></div><button className="w-full h-10 border rounded mt-4" onClick={onClose}>Close</button></div></div>; }
