import React, { useEffect, useState } from "react";
import { Clock, Percent, Printer, Save, ShieldCheck } from "lucide-react";
import { fetchSettings, setSetting } from "@/lib/catalogStore";

const DEFAULTS = { tax_rate: "8", biz_name: "Your Café Name", biz_address: "1234 Main Street, Your City", biz_phone: "123-456-7890", delivery_fee: "3.50", hours: "7:00 – 22:00", printer: "Star TSP143 (USB)" };
export default function Settings() {
  const [values, setValues] = useState(DEFAULTS), [loading, setLoading] = useState(true), [error, setError] = useState(""), [saving, setSaving] = useState(false), [saved, setSaved] = useState(false);
  useEffect(() => { let cancelled = false; fetchSettings().then((rows) => { if (!cancelled) setValues({ ...DEFAULTS, ...Object.fromEntries(rows.map((row) => [row.key, row.value])) }); }).catch((err) => !cancelled && setError(err.message)).finally(() => !cancelled && setLoading(false)); return () => { cancelled = true; }; }, []);
  const set = (key, value) => setValues((current) => ({ ...current, [key]: value }));
  const save = async () => { setSaving(true); try { await Promise.all(Object.entries(values).map(([key, value]) => setSetting(key, value))); setSaved(true); setTimeout(() => setSaved(false), 2000); } catch (err) { alert(err.message); } finally { setSaving(false); } };
  if (loading || error) return <div className={`px-8 py-7 text-sm ${error ? "text-red-400" : "text-[hsl(var(--muted-foreground))]"}`}>{error ? `Couldn't load settings: ${error}` : "Loading settings..."}</div>;
  return <div className="px-8 py-7 max-w-2xl"><h1 className="text-[28px] font-medium mb-5">Settings</h1><Section icon={Printer} title="Receipt header"><div className="space-y-2">{[["biz_name", "Business name"], ["biz_address", "Address"], ["biz_phone", "Phone"]].map(([key, label]) => <input key={key} aria-label={label} value={values[key]} placeholder={label} onChange={(e) => set(key, e.target.value)} className="w-full h-10 px-3 rounded border" />)}</div></Section><Section icon={Percent} title="Tax rate"><input aria-label="Tax rate" type="number" step="0.1" value={values.tax_rate} onChange={(e) => set("tax_rate", e.target.value)} className="w-24 h-10 px-3 rounded border" /> <span className="text-sm">% applied to every order subtotal</span></Section><Section icon={Percent} title="Delivery fee"><input aria-label="Delivery fee" type="number" step="0.5" value={values.delivery_fee} onChange={(e) => set("delivery_fee", e.target.value)} className="w-24 h-10 px-3 rounded border" /> <span className="text-sm">flat fee for delivery orders</span></Section><Section icon={Clock} title="Business hours"><input value={values.hours} onChange={(e) => set("hours", e.target.value)} className="w-full h-10 px-3 rounded border" /></Section><Section icon={Printer} title="Printer & hardware"><select value={values.printer} onChange={(e) => set("printer", e.target.value)} className="w-full h-10 px-3 rounded border"><option>Star TSP143 (USB)</option><option>Epson TM-m30 (Bluetooth)</option><option>Star TSP654 (LAN)</option><option>No printer (digital receipts only)</option></select></Section><Section icon={ShieldCheck} title="Security & PCI"><p className="text-xs text-[hsl(var(--muted-foreground))]">Card data is handled by the payment processor and stock changes are audit-logged.</p></Section><button onClick={save} disabled={saving} className="h-10 px-4 rounded bg-[hsl(var(--primary))] text-white text-sm flex gap-2 items-center disabled:opacity-40"><Save size={16} />{saving ? "Saving..." : saved ? "Saved" : "Save settings"}</button></div>;
}
function Section({ icon: Icon, title, children }) { return <section className="rounded-xl bg-[hsl(var(--card))] border p-5 mb-4"><div className="flex items-center gap-2 mb-3 text-sm font-medium"><Icon size={16} />{title}</div>{children}</section>; }
