import React, { useEffect, useState } from "react";
import { Clock, Pencil, Plus, Trash2, Users, X } from "lucide-react";
import { clockIn, clockOutShift, createStaffMember, deleteStaffMember, fetchShifts, fetchStaff, updateStaffMember } from "@/lib/catalogStore";

export default function StaffShift() {
  const [staff, setStaff] = useState([]), [shifts, setShifts] = useState([]), [editing, setEditing] = useState(null), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  useEffect(() => { let cancelled = false; Promise.all([fetchStaff(), fetchShifts()]).then(([members, allShifts]) => { if (!cancelled) { setStaff(members); setShifts(allShifts); } }).catch((err) => !cancelled && setError(err.message)).finally(() => !cancelled && setLoading(false)); return () => { cancelled = true; }; }, []);
  const openShiftFor = (staffId) => shifts.find((shift) => shift.staff_id === staffId && shift.clock_out === null);
  const toggleClock = async (member) => { const open = openShiftFor(member.id); const amount = prompt(open ? `Till amount at the end of ${member.name}'s shift?` : `Starting till amount for ${member.name}'s shift?`, open ? "0" : "200"); if (amount === null) return; const till = Number(amount); if (!Number.isFinite(till)) return alert("Enter a valid till amount."); try { const saved = open ? await clockOutShift(open.id, till) : await clockIn({ staff_id: member.id, till_start: till }); setShifts((current) => open ? current.map((s) => s.id === saved.id ? saved : s) : [...current, saved]); } catch (err) { alert(err.message); } };
  const save = async (member) => { try { if (member.id) { const saved = await updateStaffMember(member.id, member); setStaff((current) => current.map((s) => s.id === saved.id ? saved : s)); } else { const saved = await createStaffMember({ ...member, active: true }); setStaff((current) => [...current, saved]); } setEditing(null); } catch (err) { alert(err.message); } };
  const remove = async (member) => { if (!confirm(`Delete ${member.name}?`)) return; try { await deleteStaffMember(member.id); setStaff((current) => current.filter((s) => s.id !== member.id)); } catch (err) { alert(err.message); } };
  if (loading || error) return <div className={`px-8 py-7 text-sm ${error ? "text-red-400" : "text-[hsl(var(--muted-foreground))]"}`}>{error ? `Couldn't load staff: ${error}` : "Loading staff..."}</div>;
  const onShift = staff.filter((member) => openShiftFor(member.id)).length;
  return <div className="px-8 py-7"><div className="flex justify-between mb-5"><h1 className="text-[28px] font-medium">Staff & shifts</h1><button onClick={() => setEditing({ name: "", role: "cashier", active: true })} className="h-10 px-4 rounded bg-[hsl(var(--primary))] text-white text-sm flex gap-1 items-center"><Plus size={16} />Add staff</button></div><div className="grid grid-cols-2 gap-4 mb-5"><Stat icon={Users} label="Clocked in" value={onShift} /><Stat icon={Clock} label="Total staff" value={staff.length} /></div><div className="rounded-xl bg-[hsl(var(--card))] border overflow-hidden"><table className="w-full text-sm"><thead><tr className="text-left text-xs border-b text-[hsl(var(--muted-foreground))]"><th className="px-4 py-3">Staff</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{staff.map((member) => { const open = openShiftFor(member.id); return <tr className="border-b last:border-0" key={member.id}><td className="px-4 py-3 font-medium">{member.name}</td><td className="px-4 py-3 capitalize">{member.role}</td><td className="px-4 py-3">{open ? "On shift" : "Off"}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><button title="Edit" onClick={() => setEditing(member)}><Pencil size={15} /></button><button title="Delete" onClick={() => remove(member)}><Trash2 size={15} /></button><button onClick={() => toggleClock(member)} className="border rounded px-3 h-8">{open ? "Clock out" : "Clock in"}</button></div></td></tr>; })}</tbody></table></div>{editing && <Editor member={editing} onClose={() => setEditing(null)} onSave={save} />}</div>;
}
function Stat({ icon: Icon, label, value }) { return <div className="rounded-xl bg-[hsl(var(--card))] border p-5"><div className="flex gap-2 text-xs text-[hsl(var(--muted-foreground))]"><Icon size={16} />{label}</div><div className="text-2xl text-[hsl(var(--primary))]">{value}</div></div>; }
function Editor({ member, onClose, onSave }) { const [form, setForm] = useState(member); const set = (key, value) => setForm((current) => ({ ...current, [key]: value })); return <div className="fixed inset-0 z-50 bg-black/30 flex items-center justify-center" onClick={onClose}><div className="w-full max-w-sm p-5 rounded-xl bg-[hsl(var(--card))]" onClick={(e) => e.stopPropagation()}><div className="flex justify-between mb-4"><span>{member.id ? "Edit staff member" : "New staff member"}</span><button onClick={onClose}><X size={18} /></button></div><label className="text-sm">Name<input value={form.name} onChange={(e) => set("name", e.target.value)} className="block w-full h-10 border rounded px-3 mt-1 mb-3" /></label><label className="text-sm">Role<select value={form.role} onChange={(e) => set("role", e.target.value)} className="block w-full h-10 border rounded px-3 mt-1"><option value="admin">Admin</option><option value="manager">Manager</option><option value="cashier">Cashier</option></select></label><div className="flex gap-2 mt-4"><button onClick={onClose} className="flex-1 h-10 border rounded">Cancel</button><button onClick={() => onSave(form)} className="flex-1 h-10 rounded bg-[hsl(var(--primary))] text-white">Save</button></div></div></div>; }
